FROM mcr.microsoft.com/devcontainers/python:{{ python_version }}

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    zsh \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.7 /uv /uvx /usr/local/bin/

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

RUN corepack enable && corepack prepare pnpm@10 --activate

RUN curl -sL -o /usr/local/bin/hadolint \
    "https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64" \
    && chmod +x /usr/local/bin/hadolint

WORKDIR /workspace