globs:
  - '*.md'

ignores:
  - 'template/**'
  - 'node_modules/**'
  - '.venv/**'
  - '.pre-commit-cache/**'

config:
  default: true

  MD013:
    line_length: 88
    code_blocks: false
    tables: false
    headings: false

  MD024:
    siblings_only: true

  MD041: true

  MD046:
    style: fenced

  MD048:
    style: backtick
