globs:
  - '*.md'

ignores:
  - 'template/**'
  - 'node_modules/**'
  - '.venv/**'
  - '.pre-commit-cache/**'

config:
  line-length:
    line_length: 120
    heading_line_length: 120
    code_block_line_length: 120

  no-duplicate-heading:
    siblings_only: true

  no-inline-html: false
  no-trailing-punctuation: false
