"""AI module configuration -- model settings, provider defaults, RAG pipeline constants."""


from ..core.value_objects.model_config import (  # noqa: F401
    DEFAULT_MAX_TOKENS,
    DEFAULT_TEMPERATURE,
)

MAX_TOKEN_LIMIT = 128_000

MAX_PROMPT_LENGTH = 32_000

MAX_SYSTEM_PROMPT_LENGTH = 8_000

DEFAULT_CHAT_MODEL = "gpt-4o"

DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"

DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-6"

DEFAULT_SENTENCE_TRANSFORMER_MODEL = "all-MiniLM-L6-v2"

DEFAULT_CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"


DEFAULT_EMBEDDING_DIMENSION = 1536

DEFAULT_SIMILARITY_TOP_K = 5


DEFAULT_CHUNK_SIZE = 512

DEFAULT_CHUNK_OVERLAP = 64

DEFAULT_GRAPH_NEIGHBOR_LIMIT = 10

DEFAULT_HISTORY_WINDOW = 10

DEFAULT_AGENT_MAX_STEPS = 10

DEFAULT_POOL_MIN_SIZE = 1

DEFAULT_POOL_MAX_SIZE = 5

EVAL_MAX_TOKENS = 256

EXTRACTION_INPUT_LIMIT = 4_000

DEFAULT_CONVERSATION_LIMIT = 50

DEFAULT_CONVERSATION_TTL = 86_400

DEFAULT_SEARCH_TOP_K = 10

RECURSION_LIMIT_MULTIPLIER = 2

SOURCE_TEXT_PREVIEW_LENGTH = 500
